using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Moneris;
using team5_payment.Models;

namespace team5_payment.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PaymentsController : ControllerBase
    {
        //POST: /api/payments
        [HttpPost("SaveCard")]
        public ActionResult SaveCard(SaveCard saveCard)
        {
            /*
             * For Testing:
             * 
             * pan: "4242424242424242";
             * expDate: "1912"
             * streetNumber: "212"
             * streetName: "Payton Street"
             * zipCode: "M1M1M1"
             */

            //Mandatory info given by the store
            string store_id = "store5";
            string api_token = "yesguy";

            string pan = saveCard.Pan;
            string expdate = saveCard.ExpDate;
            string crypt_type = "7"; //crypt type 7 for ecommerce

            AvsInfo avsCheck = new AvsInfo();
            avsCheck.SetAvsStreetNumber(saveCard.StreetNumber);
            avsCheck.SetAvsStreetName(saveCard.StreetName);
            avsCheck.SetAvsZipCode(saveCard.ZipCode);

            ResAddCC resaddcc = new ResAddCC();
            resaddcc.SetPan(pan);
            resaddcc.SetExpDate(expdate);
            resaddcc.SetCryptType(crypt_type);

            //Mandatory - Credential on File details
            CofInfo cof = new CofInfo();
            cof.SetIssuerId("139X3130ASCXAS9"); //can be obtained by performing card verification

            resaddcc.SetCofInfo(cof);

            HttpsPostRequest mpgReq = new HttpsPostRequest();
            mpgReq.SetTestMode(true); //false or comment out this line for production transactions
            mpgReq.SetStoreId(store_id);
            mpgReq.SetApiToken(api_token);
            mpgReq.SetProcCountryCode("CA");
            mpgReq.SetTransaction(resaddcc);
            mpgReq.Send();

            try
            {
                
                Receipt receipt = mpgReq.GetReceipt();
                var response = new { Id = receipt.GetDataKey(), Success = receipt.GetResSuccess()}; 

                if (response.Success == "true")
                    return Created(new Uri(Request.GetDisplayUrl() + "/" + response.Id), response);
                else
                    return BadRequest();
            }

            catch (Exception e)
            {
                return BadRequest(e.ToString());
            }
        }

        [HttpPost("ProcessSavedPayment")]
        public ActionResult ProcessSavedPayment()
        {
            string order_id = "Test" + DateTime.Now.ToString("yyyyMMddhh");
            string store_id = "store5";
            string api_token = "yesguy";
            string amount = "5.00";
            string pan = "4242424242424242";
            string expdate = "1901"; //YYMM format
            string crypt = "7";
            string processing_country_code = "CA";
            bool status_check = false;

            //CofInfo cof = new CofInfo();
            //cof.SetPaymentIndicator("U");
            //cof.SetPaymentInformation("2");
            //cof.SetIssuerId("168451306048014");

            Purchase purchase = new Purchase();
            purchase.SetOrderId(order_id);
            purchase.SetAmount(amount);
            purchase.SetPan(pan);
            purchase.SetExpDate(expdate);
            purchase.SetCryptType(crypt);
            purchase.SetDynamicDescriptor("2134565");
            //purchase.SetWalletIndicator(""); //Refer to documentation for details
            //purchase.SetCofInfo(cof);

            //purchase.SetCmId("8nAK8712sGaAkls56"); //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant

            HttpsPostRequest mpgReq = new HttpsPostRequest();
            mpgReq.SetProcCountryCode(processing_country_code);
            mpgReq.SetTestMode(true); //false or comment out this line for production transactions
            mpgReq.SetStoreId(store_id);
            mpgReq.SetApiToken(api_token);
            mpgReq.SetTransaction(purchase);
            mpgReq.SetStatusCheck(status_check);
            mpgReq.Send();

            try
            {
                Receipt receipt = mpgReq.GetReceipt();
                var response = new { Id = receipt.GetDataKey(), Success = receipt.GetResSuccess() };
                return Ok(response);
                //if (response.Success == "true")
                //    return Ok();
                //else
                //    return BadRequest();
            }

            catch (Exception e)
            {
                return BadRequest(e.ToString());
            }
        }

        [HttpPost("retreive")]
        public ActionResult Retreive(string data_key)
        {
            /*
             * For Testing: 
             * 
             * data_key = "Bcjvur5vxbOMzSaDH43BfFwS2"
             */

            string store_id = "store5";
            string api_token = "yesguy";
            string processing_country_code = "CA";
            bool status_check = false;

            ResLookupMasked resLookupMasked = new ResLookupMasked();
            resLookupMasked.SetDataKey(data_key);

            HttpsPostRequest mpgReq = new HttpsPostRequest();
            mpgReq.SetProcCountryCode(processing_country_code);
            mpgReq.SetTestMode(true); //false or comment out this line for production transactions
            mpgReq.SetStoreId(store_id);
            mpgReq.SetApiToken(api_token);
            mpgReq.SetTransaction(resLookupMasked);
            mpgReq.SetStatusCheck(status_check);
            mpgReq.Send();

            try
            {
                Receipt receipt = mpgReq.GetReceipt();
                var response = new
                {
                    Id = receipt.GetDataKey(),
                    Success = receipt.GetResSuccess(),
                    FirstName = receipt.GetResCustFirstName(),
                    LastName = receipt.GetResCustLastName(),
                    MaskedPan = receipt.GetResMaskedPan(),
                    ExpDate = receipt.GetResExpDate()

            };

                if (response.Success == "true")
                    return Ok(response);
                else
                    return BadRequest("one");

            }
            catch (Exception e)
            {
                return BadRequest(e.ToString());
            }
        }
    }
}
